main: de.leonheuer.skycave.jobsystem.JobSystem
name: JobSystem
version: 1.1.0
api-version: 1.16
author: Hakuyamu
depend:
  - SkyBeeCore
  - Vault

commands:
  job:
    aliases: jobs
  sell:
    aliases: ankauf
  gsell:
    aliases: gankauf, globalsell