main: de.leonheuer.skycave.jobsystem.JobSystem
name: JobSystem
version: 1.0.0
api-version: 1.16
author: Hakuyamu
depend:
  - SkyBeeCore

commands:
  job:
    aliases: jobs

permissions:
  skybee.jobsystem:
    admin: admin permission