main: de.leonheuer.skycave.jobsystem.JobSystem
name: JobSystem
version: 2.0.0
api-version: 1.18
author: Hakuyamu
depend:
  - SkyBeeCore
  - Vault

commands:
  job:
    aliases: jobs
  sell:
    aliases: ankauf
  gsell:
    aliases: gankauf, globalsell